### PR TITLE
Updating all the repos after removing duplicate files.

### LINKED ISSUE #89: Remove duplicate files like pack.hpp, type_traits.hpp, unbounded_shift.hpp, endian_shift.hpp etc.
Files pack.hpp, type_traits.hpp, unbounded_shift.hpp, endian_shift.hpp are copied into all the repos. I'm not even sure which repo is supposed to have these file, but they use the same #ifdef-s, which means that we need to keep them identical, otherwise it's not clear which one will be used in the crypto3-zk project. (many of them will get included from different sources)

### PR DESCRIPTION
**Pull request by martun**

### CODE REVIEW

**Comment by nemothenoone** [comment]
This one cannot be merged in. Submodules others than zk which can work without zk, also use them.

**Comment by martun** [comment]
> This one cannot be merged in. Submodules others than zk which can work without zk, also use them.

@nemothenoone Ok, but we need to decide where to put these files. Now they are in 7 copies each, each copy slightly different, and all with the same #ifndef-s. You are never sure which one gets used from zk...

I left 1 copy of each file in the hash repo, can't everyone else depend on the crypto3-hash? They will not need to change even the #include statements, just add dependency on crypto3-hash.

**Comment by nemothenoone** [comment]
@martun We can emplace them in some most low-level library? Something like https://github.com/NilFoundation/crypto3-block?

**Comment by martun** [comment]
> @martun We can emplace them in some most low-level library? Something like https://github.com/NilFoundation/crypto3-block?

Yep, we can. @nkaskov do you agree?

**Pull request closed without merging**
